FROM ruby:2.3.0

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev

# Create the workdir
RUN mkdir /app
WORKDIR /app

# Copy gemfiles and install gem dependencies
ADD Gemfile /app/Gemfile
ADD Gemfile.lock /app/Gemfile.lock
RUN bundle install --jobs 20 --retry 5 --without development test

ENV RAILS_ENV production
ENV RACK_ENV production

ADD . /app

CMD ["rails", "s", "-p", "80", "-b", "0.0.0.0"]
